---
language: python
python: "2.7"

env:
  - COMMCARE_CLOUD_ENVIRONMENTS=.

before_install:
  - pip install pip-tools

install:
  - pip-sync
  - manage-commcare-cloud install
  - manage-commcare-cloud configure --quiet

script:
  - manage-commcare-cloud test-environments
