---
language: python
python: "2.7"

before_install:
  - pip install pip-tools

install:
  - pip-sync
  - manage-commcare-cloud install
  - COMMCARE_CLOUD_ENVIRONMENTS='environments' manage-commcare-cloud configure --quiet

script:
  - manage-commcare-cloud test-environments
